/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.96
 * Generated at: 2019-11-14 04:56:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.ArrayList;
import dbConnection.ProvideConnection;

public final class takeAttendance_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, shrink-to-fit=no\">\r\n");
      out.write("    <title>Attendance-AMS</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/fonts/font-awesome.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/fonts/ionicons.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/CDRReporteCuotas.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/gradient-navbar-1.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/gradient-navbar.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/Header-Blue.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/Login-Form-Clean.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/Login-Form-Dark.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/Pretty-Registration-Form.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/Navbar---Apple-1.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/Navbar---Apple.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/Profile-Edit-Form-1.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/Profile-Edit-Form.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/Registration-Form-with-Photo-1.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/Registration-Form-with-Photo.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/styles.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div style=\"padding: 22px;\">\r\n");
      out.write("         \t\t\t\t\r\n");
      out.write("\t\t\t\t\t<nav class=\"navbar navbar-light navbar-expand bg-white shadow mb-4 topbar static-top\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-link d-md-none rounded-circle mr-3\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"sidebarToggleTop\" type=\"button\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-bars\"></i>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav navbar-nav flex-nowrap ml-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"d-none d-sm-block topbar-divider\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<li role=\"presentation\" class=\"nav-item dropdown no-arrow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"nav-item dropdown no-arrow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a data-toggle=\"dropdown\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"dropdown-toggle nav-link\" href=\"#\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"d-none d-lg-inline mr-2 text-gray-600 small\">");
      out.print(session.getAttribute("firstname"));
      out.write("</span><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"border rounded-circle img-profile\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"assets/img/avatars/avatar5.jpeg\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div role=\"menu\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"dropdown-menu shadow dropdown-menu-right animated--grow-in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a role=\"presentation\" class=\"dropdown-item\" href=\"Logout\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmethod=\"post\" value=\"logout\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400\"></i>Logout</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("            <h3 class=\"text-center\" style=\"padding: 6px;\">Attendance</h3>\r\n");
      out.write(" \t\t\t<form action=\"takeAttendance.jsp\">\r\n");
      out.write(" \t\t\t<div class=\"col-sm-4 col-md-4\">\r\n");
      out.write("\t\t\t\t<label>Subject<select id=\"subject\" name=\"subject\" class=\"form-control\" \r\n");
      out.write("\t\t\t\t\t><optgroup>\r\n");
      out.write("\t\t\t\t\t\t\t");

									session=request.getSession();
									String regid=(String)session.getAttribute("regno");
									String query="select subject,attendance_table,course,branch,semester from subject_assigned_to_faculty where regid='"+regid+"';";
									Connection con = ProvideConnection.getCon();
									Statement st = con.createStatement();
									ResultSet rs = st.executeQuery(query);
									ArrayList<String> assignSubject=new ArrayList<String>();
									int i=0;
									while(rs!=null&&rs.next())
									{
										String subject = rs.getString(1);
										String course=rs.getString(3);
										String branch=rs.getString(4);
										String semester=rs.getString(5);
										String table=rs.getString(2);
										Statement stSubject=con.createStatement();
										ResultSet sub=stSubject.executeQuery("select subjectname from subjects where subjectid='"+subject+"';");
										sub.next();
										String subjectName=sub.getString(1);
										assignSubject.add(table);
										String opt=null;
										if(course.equals("mca"))
										opt=subjectName+" "+course+" "+semester;
										else
										opt=subjectName+" "+course+" "+branch+" "+semester;
										out.println("<option value=\""+i+"\">"+opt+"</option>");
										i++;
									}
									session.setAttribute("list", assignSubject);
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" name=\"submit\" value=\"Student List\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write(" \t\t\t</form>\r\n");
      out.write(" \t\t\t<form action=\"TakeAttendance\" method=\"post\">\r\n");
      out.write("             <div class=\"table-responsive\">\r\n");
      out.write("                <table class=\"table\">\r\n");
      out.write("                    <thead class=\"text-center\">\r\n");
      out.write("                        <tr class=\"text-center\">\r\n");
      out.write("                            <th>Registration No &nbsp;</th>\r\n");
      out.write("                            <th>Student Name &nbsp;</th>\r\n");
      out.write("                            <th>Present/Absent &nbsp;</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");
	
                        	ArrayList<String>  al=(ArrayList<String>)session.getAttribute("list");
                        	String sub=request.getParameter("subject");
                        	if(al!=null&&sub!=null)
                        	{
                        		int pos=Integer.parseInt(request.getParameter("subject"));
                        		String table=al.get(pos);
                        		//System.out.println(table);
                        		Statement s=con.createStatement();
                        		ResultSet stList=s.executeQuery("select regno ,name from "+table+";");
                        		ArrayList<String> regNoList=new ArrayList<String>();
                        		while(stList.next())
                        		{
                        			String regno=stList.getString(1);
                        			String name=stList.getString(2);
                        			regNoList.add(regno);
                        			out.println("<tr><td>"+regno+"</td><td>"+name+"</td><td><input type=\"checkbox\" name=\""+regno+"\"></td></tr>");
                        		}
                        		session.removeAttribute("list");
								session.setAttribute("table",table);
                        		session.setAttribute("list", regNoList);
                        	}
                        	al=null;
							con.close();
							st.close();
                        	
      out.write("\r\n");
      out.write("                    </thead>\r\n");
      out.write("            </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        \t\t<div class=\"col-sm-3 col-md-3\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" name=\"submit\" value=\"SAVE\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("        \t\t\r\n");
      out.write("            </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/Navbar---Apple.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/Profile-Edit-Form.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
